version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Check if the tag already exist
          command: |
            set +e
            [[ "$(git show -s --format=%B)" == "Releasing Kamus CLI"* ]] && circleci step halt
            . version
            GIT_TAG_LATEST="$(git tag --sort=creatordate | awk '/'${KAMUS_CLI_VERSION//-*/}'/{ a=$1 ; rc = 1 } END{print a ; exit !rc }')"
            if [[ "${KAMUS_CLI_VERSION//-*/}" == "${GIT_TAG_LATEST//-*/}" ]]; then
              [[ "${GIT_TAG_LATEST}" != *"-"* ]] && GIT_TAG_LATEST=0
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-$((${GIT_TAG_LATEST//*-/} + 1))"
            else
              GIT_TAG="${KAMUS_CLI_VERSION}"
            fi
            sed -i "s/\(KAMUS_CLI_VERSION\).*/\1=${GIT_TAG}/g" version
            cat version
      - run:
          name: Publish the tag
          command: |
            [[ "$(git show -s --format=%B)" == "Releasing Kamus CLI"* ]] && circleci step halt
            . version
            git config --global user.email "circleci@lozanomatheus.com"
            git config --global user.name "circleci"
            sed -i "s/latest/${KAMUS_CLI_VERSION}/g" README.md
            git add version || true
            git commit -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}." || true
            git push --all
            git add README.md || true
            git commit -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}." || true
            git tag -a ${KAMUS_CLI_VERSION} -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}."
            git push origin ${KAMUS_CLI_VERSION}

      - add_ssh_keys:
          fingerprints:
            - "3f:2f:d1:f7:45:4f:73:b4:87:ce:ca:ba:02:a5:2e:54"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
